-- Seed companies data
-- Run this in Supabase SQL Editor if the Node.js script has network issues

INSERT INTO companies (name, domain, logo) VALUES
  ('Meta', 'meta.com', 'https://logo.clearbit.com/meta.com'),
  ('Apple', 'apple.com', 'https://logo.clearbit.com/apple.com'),
  ('Amazon', 'amazon.com', 'https://logo.clearbit.com/amazon.com'),
  ('Netflix', 'netflix.com', 'https://logo.clearbit.com/netflix.com'),
  ('Google', 'google.com', 'https://logo.clearbit.com/google.com'),
  ('Microsoft', 'microsoft.com', 'https://logo.clearbit.com/microsoft.com'),
  ('Tesla', 'tesla.com', 'https://logo.clearbit.com/tesla.com'),
  ('Uber', 'uber.com', 'https://logo.clearbit.com/uber.com'),
  ('Airbnb', 'airbnb.com', 'https://logo.clearbit.com/airbnb.com'),
  ('Stripe', 'stripe.com', 'https://logo.clearbit.com/stripe.com'),
  ('Salesforce', 'salesforce.com', 'https://logo.clearbit.com/salesforce.com'),
  ('Oracle', 'oracle.com', 'https://logo.clearbit.com/oracle.com'),
  ('Adobe', 'adobe.com', 'https://logo.clearbit.com/adobe.com'),
  ('IBM', 'ibm.com', 'https://logo.clearbit.com/ibm.com'),
  ('Intel', 'intel.com', 'https://logo.clearbit.com/intel.com'),
  ('NVIDIA', 'nvidia.com', 'https://logo.clearbit.com/nvidia.com'),
  ('AMD', 'amd.com', 'https://logo.clearbit.com/amd.com'),
  ('Qualcomm', 'qualcomm.com', 'https://logo.clearbit.com/qualcomm.com'),
  ('OpenAI', 'openai.com', 'https://logo.clearbit.com/openai.com'),
  ('Anthropic', 'anthropic.com', 'https://logo.clearbit.com/anthropic.com'),
  ('SpaceX', 'spacex.com', 'https://logo.clearbit.com/spacex.com'),
  ('Coinbase', 'coinbase.com', 'https://logo.clearbit.com/coinbase.com'),
  ('Databricks', 'databricks.com', 'https://logo.clearbit.com/databricks.com'),
  ('Snowflake', 'snowflake.com', 'https://logo.clearbit.com/snowflake.com'),
  ('Palantir', 'palantir.com', 'https://logo.clearbit.com/palantir.com'),
  ('Figma', 'figma.com', 'https://logo.clearbit.com/figma.com'),
  ('Notion', 'notion.so', 'https://logo.clearbit.com/notion.so'),
  ('Canva', 'canva.com', 'https://logo.clearbit.com/canva.com'),
  ('Discord', 'discord.com', 'https://logo.clearbit.com/discord.com'),
  ('Roblox', 'roblox.com', 'https://logo.clearbit.com/roblox.com'),
  ('Twitter', 'twitter.com', 'https://logo.clearbit.com/twitter.com'),
  ('LinkedIn', 'linkedin.com', 'https://logo.clearbit.com/linkedin.com'),
  ('Snap', 'snap.com', 'https://logo.clearbit.com/snap.com'),
  ('Pinterest', 'pinterest.com', 'https://logo.clearbit.com/pinterest.com'),
  ('Reddit', 'reddit.com', 'https://logo.clearbit.com/reddit.com'),
  ('TikTok', 'tiktok.com', 'https://logo.clearbit.com/tiktok.com'),
  ('Goldman Sachs', 'goldmansachs.com', 'https://logo.clearbit.com/goldmansachs.com'),
  ('JPMorgan Chase', 'jpmorganchase.com', 'https://logo.clearbit.com/jpmorganchase.com'),
  ('Morgan Stanley', 'morganstanley.com', 'https://logo.clearbit.com/morganstanley.com'),
  ('Citadel', 'citadel.com', 'https://logo.clearbit.com/citadel.com'),
  ('BlackRock', 'blackrock.com', 'https://logo.clearbit.com/blackrock.com'),
  ('Robinhood', 'robinhood.com', 'https://logo.clearbit.com/robinhood.com'),
  ('McKinsey & Company', 'mckinsey.com', 'https://logo.clearbit.com/mckinsey.com'),
  ('Boston Consulting Group', 'bcg.com', 'https://logo.clearbit.com/bcg.com'),
  ('Bain & Company', 'bain.com', 'https://logo.clearbit.com/bain.com'),
  ('Deloitte', 'deloitte.com', 'https://logo.clearbit.com/deloitte.com'),
  ('Accenture', 'accenture.com', 'https://logo.clearbit.com/accenture.com'),
  ('Shopify', 'shopify.com', 'https://logo.clearbit.com/shopify.com'),
  ('eBay', 'ebay.com', 'https://logo.clearbit.com/ebay.com'),
  ('Walmart', 'walmart.com', 'https://logo.clearbit.com/walmart.com'),
  ('Target', 'target.com', 'https://logo.clearbit.com/target.com'),
  ('Cloudflare', 'cloudflare.com', 'https://logo.clearbit.com/cloudflare.com'),
  ('MongoDB', 'mongodb.com', 'https://logo.clearbit.com/mongodb.com'),
  ('Atlassian', 'atlassian.com', 'https://logo.clearbit.com/atlassian.com'),
  ('GitLab', 'gitlab.com', 'https://logo.clearbit.com/gitlab.com'),
  ('GitHub', 'github.com', 'https://logo.clearbit.com/github.com'),
  ('Vercel', 'vercel.com', 'https://logo.clearbit.com/vercel.com'),
  ('Electronic Arts', 'ea.com', 'https://logo.clearbit.com/ea.com'),
  ('Activision Blizzard', 'activisionblizzard.com', 'https://logo.clearbit.com/activisionblizzard.com'),
  ('Epic Games', 'epicgames.com', 'https://logo.clearbit.com/epicgames.com'),
  ('Riot Games', 'riotgames.com', 'https://logo.clearbit.com/riotgames.com'),
  ('Lyft', 'lyft.com', 'https://logo.clearbit.com/lyft.com'),
  ('DoorDash', 'doordash.com', 'https://logo.clearbit.com/doordash.com'),
  ('Instacart', 'instacart.com', 'https://logo.clearbit.com/instacart.com'),
  ('Moderna', 'modernatx.com', 'https://logo.clearbit.com/modernatx.com'),
  ('Pfizer', 'pfizer.com', 'https://logo.clearbit.com/pfizer.com'),
  ('Johnson & Johnson', 'jnj.com', 'https://logo.clearbit.com/jnj.com'),
  ('Zoom', 'zoom.us', 'https://logo.clearbit.com/zoom.us'),
  ('Slack', 'slack.com', 'https://logo.clearbit.com/slack.com'),
  ('Dropbox', 'dropbox.com', 'https://logo.clearbit.com/dropbox.com'),
  ('Twilio', 'twilio.com', 'https://logo.clearbit.com/twilio.com'),
  ('Square', 'squareup.com', 'https://logo.clearbit.com/squareup.com'),
  ('PayPal', 'paypal.com', 'https://logo.clearbit.com/paypal.com')
ON CONFLICT (domain) DO NOTHING;

-- Verify the insert
SELECT COUNT(*) as total_companies FROM companies;
